hmcts/lau-case-backend

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- build.gradle
- src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/config/SwaggerPublisherTest.java
- src/integrationTest/resources/application.yaml
https://tools.hmcts.net/jira/browse/LAU-32
Update to fix Jenkinsfile
```
[ ] Yes
[x] No
```
> LAU-32: Jenkinsfile updates.

- README.md
- charts/lau-case-backend/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/LAU-94
Test building PR.
```
[ ] Yes
[x] No
```
> LAU-94: Branch checkout build test

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- build.gradle
- charts/lau-case-backend/Chart.yaml
- charts/lau-case-backend/values.yaml
- docker-compose.yml
- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/client/IdamServiceClient.java
- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseViewTest.java
- src/functionalTest/resources/application-functional.yaml
- src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/config/SwaggerPublisherTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/controllers/GetWelcomeTest.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/authorization/AuthService.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/authorization/AuthorisedServices.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/authorization/RestApiPreInvokeInterceptor.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/config/AuthServiceConfiguration.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/config/RestApiPreInvokeConfiguration.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/exceptions/InvalidAuthenticationException.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/authorization/AuthServiceTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/authorization/AuthorisedServicesTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/handlers/RestApiPreInvokeConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/handlers/RestApiPreInvokeInterceptorTest.java
https://tools.hmcts.net/jira/browse/LAU-84
S2S impelentation.
```
[ ] Yes
[x] No
```
> LAU-84 Check S2S token to confirm invoking service is authorised to POST

- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseSearchTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/controllers/GetWelcomeTest.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/config/RestApiPreInvokeConfiguration.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/constants/ExceptionMessageConstants.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseSearchController.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseViewController.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/domain/CaseSearchAudit.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/domain/CaseSearchAuditCases.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/dto/SearchLog.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditRepository.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/request/CaseSearchPostRequest.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseSearchService.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/utils/InputParamsVerifier.java
- src/main/resources/db/migration/V001__Schema.sql
- src/main/resources/h2/V001__Schema.sql
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseSearchControllerTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseViewControllerTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditRepositoryTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseViewAuditRepositoryStartEndTimeTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseViewAuditRepositoryTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseSearchServiceTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/InputParamsNotEmptyVerifierTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/InputParamsVerifierPostExceptionTest.java
https://tools.hmcts.net/jira/browse/LAU-23
New POST /audit/caseSearch endpoint
```
[ ] Yes
[x] No
```
> LAU-23 Build new POST /audit/caseSearch endpoint

- src/main/java/uk/gov/hmcts/reform/laubackend/cases/config/SwaggerConfiguration.java
https://tools.hmcts.net/jira/browse/LAU-142
Fixed api docs errors reported within swagger editor
[ ] Yes
[x] No
> API-Docs-Erros

- src/main/java/uk/gov/hmcts/reform/laubackend/cases/constants/RegexConstants.java
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/LAU-195
Minor updates to make LAU Backend work with CCD.
```
[ ] Yes
[x] No
```
> LAU-195: Minor change to log_timestamp and updating authorised services.

- Jenkinsfile_CNP
Sync master to ITHC and Perftest
```
[ ] Yes
[x] No
```
> LAU-1234: Update to sync to new environments

- src/main/java/uk/gov/hmcts/reform/laubackend/cases/constants/CommonConstants.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseActionController.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseSearchController.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseActionControllerTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseSearchControllerTest.java
Add ServiceAuthorisation header for Swagger
```
[ ] Yes
[ x] No
```
> Add ServiceAuthorization header to the API's for Swagger.

- src/main/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseActionController.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseSearchController.java
https://tools.hmcts.net/jira/browse/LAU-196?workflowName=LAU%3A+Workflow+v2&stepId=22
Swagger Documentation (Service Authorisation)
[ ] Yes
[x] No
> LAU-196 Swagger documentation for the Service Authorisation fields

- Jenkinsfile_nightly
[LAU-223 Disable Fortify](https://tools.hmcts.net/jira/browse/LAU-223)
LAU-223 Disable Fortify
```
[ ] Yes
[x] No
```
> LAU-223: Disable Fortify

- build.gradle
https://tools.hmcts.net/jira/browse/LAU-226
LAU-226: Upgrade Log4j to 2.15.0
```
[ ] Yes
[x] No
```
> LAU-226: Upgrade Log4j to 2.15.0

- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/serenityfunctionaltests/model/CaseActionResponseVO.java
- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/serenityfunctionaltests/model/CaseSearchGetResponseVO.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/response/CaseActionGetResponse.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/response/CaseSearchGetResponse.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseActionService.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseSearchService.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseActionAuditRepositoryTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditRepositoryTest.java
https://tools.hmcts.net/jira/browse/LAU-208
Add total records for all GET requests
```
[ ] Yes
[x] No
```
> LAU-208 Update BE to allow latest FE changes

- charts/lau-case-backend/values.preview.template.yaml
- src/integrationTest/resources/features/get_case_action.feature
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseActionAuditRepository.java
- src/main/resources/db/migration/V002__Schema.sql
https://tools.hmcts.net/jira/browse/LAU-220
Fix case sensitivity in Case Audit/IdAM search page
```
[ ] Yes
[x] No
```
> LAU-220 Fix case sensitivity in Case Audit/IdAM search page.

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/serenityfunctionaltests/runner/CaseSearchApiTest.java
- src/integrationTest/resources/application.properties
- src/integrationTest/resources/application.yaml
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseActionController.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseSearchController.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseActionAuditRepositoryStartEndTimeTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseActionAuditRepositoryTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditRepositoryCaseRefTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditRepositoryTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/RemoveColumnTransformers.java
https://tools.hmcts.net/jira/browse/LAU-185
Swagger Documentation Infrastructure
[ ] Yes
[x] No
> LAU-185 fixed spelling and added 401 response code

- .travis.yml
https://tools.hmcts.net/jira/browse/LAU-230
Investigate the process of automating swaggers docs deployment
[ ] Yes
[x] No
> LAU-230 Auto generation of swagger docs

- src/main/java/uk/gov/hmcts/reform/laubackend/cases/config/SwaggerConfiguration.java
https://tools.hmcts.net/jira/browse/LAU-230
Testing autogeneration of swagger documentations
[ ] Yes
[x] No
> LAU-230 testing swagger auto doc generation

- .travis.yml
- src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/config/SwaggerPublisherTest.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/config/SwaggerConfiguration.java
https://tools.hmcts.net/jira/browse/LAU-230
Swagger docs automation via integration tests
[ ] Yes
[x] No
> LAU 230 swagger auto generation test

- .travis.yml
- src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/config/SwaggerPublisherTest.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/config/SwaggerConfiguration.java
https://tools.hmcts.net/jira/browse/LAU-230
Swagger docs github action
[ ] Yes
[X] No
> LAU-230 swagger auto generation test

- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/serenityfunctionaltests/runner/CaseSearchApiTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/bdd/CaseActionPostSteps.java
- src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/bdd/CaseSearchPostSteps.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseSearchController.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/response/CaseSearchPostResponse.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/response/SearchLogPostResponse.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseSearchService.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseSearchControllerTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseSearchServiceTest.java
https://tools.hmcts.net/jira/browse/LAU-232
Update existing LAU POST endpoints to return the DB unique id
```
[ ] Yes
[x] No
```
> LAU-232 Update existing LAU POST endpoints to return the DB unique id.

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/serenityfunctionaltests/config/EnvConfig.java
- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/serenityfunctionaltests/helper/AuthorizationHeaderHelper.java
- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/serenityfunctionaltests/utils/TestConstants.java
- src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/LAU-237
Move Idam username and password to Azure vault
```
[ ] Yes
[x] No
```
> LAU-237 Move Idam username and password to Azure vault

- src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/bdd/CaseActionPostSteps.java
- src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/helper/CaseActionPostHelper.java
- src/integrationTest/resources/features/post_case_action.feature
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/domain/CaseActionAudit.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/utils/NotEmptyInputParamsVerifier.java
- src/main/resources/db/migration/V003__Schema.sql
- src/main/resources/h2/V002__Schema.sql
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseActionAuditRepositoryTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/NotEmptyInputParamsVerifierTest.java
https://tools.hmcts.net/jira/browse/LAU-259
Make jurisdiction nullable
```
[ ] Yes
[X] No
```
> LAU-259 AAT CCD Case View Audit events without jurisdiction causing errors

- src/main/java/uk/gov/hmcts/reform/laubackend/cases/authorization/RestApiPreInvokeInterceptor.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseSearchController.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseSearchService.java
Add logging for performance issues.
```
[ ] Yes
[X] No
```
> Add logging for performance testing issues.

- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/serenityfunctionaltests/steps/CaseActionGetApiSteps.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/authorization/RestApiPreInvokeInterceptor.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseSearchController.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/domain/CaseSearchAudit.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseActionAuditRepository.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditRepository.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseActionService.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseSearchService.java
- src/main/resources/db/migration/V004__Schema.sql
Optimise lau-case queries.
Optimise lau-case queries.
```
[ ] Yes
[X] No
```
> Optimise lau-case queries.

- charts/lau-case-backend/values.preview.template.yaml
- src/main/resources/db/migration/V005__Schema.sql
https://tools.hmcts.net/jira/browse/LAU-258
Optimise lau-case backend.
```
[ ] Yes
[X] No
```
> LAU-258 Optimise lau-case backend.

- src/main/resources/db/migration/V006__Schema.sql
https://tools.hmcts.net/jira/browse/LAU-258
Remove duplicate indexes covered by other table constaints.
```
[ ] Yes
[x] No
```
> LAU-258: Remove duplcate indexes

- src/main/java/uk/gov/hmcts/reform/laubackend/cases/utils/CaseSearchHelper.java
N/A
N/A
```
[ ] Yes
[X] No
```
> Fix null case ref

- build.gradle
- src/integrationTest/resources/application.yaml
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseActionAuditRepository.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditRepository.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseActionServiceTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseSearchServiceTest.java
- src/test/resources/application.yaml
https://tools.hmcts.net/jira/browse/LAU-258
Change max page size to 10,000
```
[ ] Yes
[x] No
```
> LAU-258 Change max page size to 10,000

- src/main/java/uk/gov/hmcts/reform/laubackend/cases/utils/NotEmptyInputParamsVerifier.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/NotEmptyInputParamsVerifierTest.java
Improve POST exception logs.
Improve POST exception logs.
```
[ ] Yes
[x] No
```
> Improve POST exception logs.

- build.gradle
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/domain/CaseActionAudit.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/utils/NotEmptyInputParamsVerifier.java
- src/main/resources/db/migration/V008__Schema.sql
- src/main/resources/h2/V004__Schema.sql
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/RemoveColumnTransformers.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/NotEmptyInputParamsVerifierTest.java
https://tools.hmcts.net/jira/browse/LAU-305
Remove DB constraints and missing values check for case reference and case type id.
```
[ ] Yes
[x] No
```
> LAU-305: Updated to remove case ref and type id.

- Jenkinsfile_CNP
- build.gradle
- src/integrationTest/resources/application.yaml
- src/main/resources/application.yaml
- src/main/resources/db/migration/V009__Schema.sql
https://tools.hmcts.net/jira/browse/LAU-307
Param fix.
```
[ ] Yes
[x] No
```
> LAU-307: Testing migration with env value.

- Jenkinsfile_CNP
- build.gradle
- charts/lau-case-backend/values.yaml
- src/integrationTest/resources/application.yaml
- src/main/resources/application.yaml
- src/main/resources/bootstrap.yaml
- src/main/resources/db/migration/V009__Schema.sql
https://tools.hmcts.net/jira/browse/LAU-307
Adding env to flyway scripts.
```
[ ] Yes
[x] No
```
> Lau 307 db parameter fix

- charts/lau-case-backend/Chart.yaml
https://tools.hmcts.net/jira/browse/LAU-311
Update chart version
```
[ ] Yes
[x] No
```
> LAU-311: Update charts version

- src/test/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseActionControllerTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseSearchControllerTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseSearchServiceTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/ActionInputParamsVerifierGetExceptionTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/ActionInputParamsVerifierTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/InputParamsVerifierPostExceptionTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/NotEmptyInputParamsVerifierTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/SearchInputParamsVerifierGetExceptionTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/SearchInputParamsVerifierTest.java
Update caseRef generator not generate caseRefs with leading zero
Update caseRef generator not generate caseRefs with leading zero
```
[ ] Yes
[X] No
```
> Update caseRef generator not generate caseRefs with leading zero

- src/integrationTest/resources/application.yaml
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/constants/ExceptionMessageConstants.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/utils/InputParamsVerifierHelper.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/ActionInputParamsVerifierGetExceptionTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/ActionInputParamsVerifierTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/InputParamsVerifierPostExceptionTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/SearchInputParamsVerifierGetExceptionTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/SearchInputParamsVerifierTest.java
https://tools.hmcts.net/jira/browse/LAU-323
Improve LAU exception messages
```
[ ] Yes
[x] No
```
> LAU-323 Improve LAU exception messages

- build.gradle
https://tools.hmcts.net/jira/browse/LAU-348
Addressing vulnerabilities.
```
[ ] Yes
[x] No
```
> LAU-348 Case Backend vulnerabilities

- build.gradle
https://tools.hmcts.net/jira/browse/LAU-366
Fix for Dependency check: postgresql , CVE-2022-21724
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
> LAU-366: Dependency check postgresql

- build.gradle
https://tools.hmcts.net/jira/browse/LAU-366
Fix vulnerability
```
[ ] Yes
[x] No
```
> LAU-366: Fix vulnerability.

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-373
Update to suppress spring-plugin vulnerabilities.
```
[ ] Yes
[x] No
```
> LAU-373: Suppress vulnerability with spring-plugin.

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-377
Suppress vulnerabilities.
```
[ ] Yes
[ ] No
```
> LAU-377: Suppress springfox vulnerabilities

- security.sh
https://tools.hmcts.net/jira/browse/LAU-387
Fix security scan failures.
```
[ ] Yes
[x] No
```
> LAU-387: Update to fix security scan.

- build.gradle
https://tools.hmcts.net/jira/browse/LAU-407
This change is to fix dependency check related to CVE-2022-29885
```
[ ] Yes
[x] No
```
> LAU-407 Dependency check fix

- build.gradle
- src/integrationTest/resources/application.properties
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/config/SwaggerConfiguration.java
- src/main/resources/application.properties
https://tools.hmcts.net/jira/browse/LAU-408
This change is to fix spring Framework Dependency check
```
[ ] Yes
[x] No
```
> LAU-408 dependency check fix

- build.gradle
https://tools.hmcts.net/jira/browse/LAU-409
This change is to upgrade other libraries in lau-case-backend
```
[ ] Yes
[x] No
```
> LAU-409 Libraries Upgrade

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-414
This change is to fix dependency check
```
[ ] Yes
[x] No
```
> LAU-414 dependency check fix

- charts/lau-case-backend/Chart.yaml
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-436
This change to fix dependency check fix
```
[ ] Yes
[x] No
```
> LAU-436 depedency check fix

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-457
This change is to fix dependency check.
```
[ ] Yes
[x] No
```
> LAU-457 dependency check fixed

- charts/lau-case-backend/Chart.yaml
- charts/lau-case-backend/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/LAU-461
This change is to upgrade Java chart version 4.0.1
```
[ ] Yes
[x] No
```
> LAU-461 java chart upgrade

- src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/LAU-481
This changer is to remove config properties
```
[ ] Yes
[x] No
```
> LAU-481 removing config properties

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/LAU-481
This change is to add secrets in Jenkins
```
[ ] Yes
[x] No
```
> LAU-481 adding secreats in Jenkins

- charts/lau-case-backend/Chart.yaml
- charts/lau-case-backend/values.yaml
https://tools.hmcts.net/jira/browse/LAU-481
This change is to referencing secret value correct way
```
[ ] Yes
[x] No
```
> LAU-481 referencing properties

- Jenkinsfile_CNP
- charts/lau-case-backend/Chart.yaml
- charts/lau-case-backend/values.yaml
- src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/PCQ-481
Fix nightly-dev
```
[ ] Yes
[x] No
```
> LAU-481: Fix nightly build.

- build.gradle
https://tools.hmcts.net/jira/browse/LAU-490
Upgrade postgres library to 42.4.1.
```
[ ] Yes
[x] No
```
> LAU-490: Upgrade postgres library.

- build.gradle
https://tools.hmcts.net/jira/browse/LAU-510
This change is to fix CVE-2022-25857
```
[ ] Yes
[x] No
```
> LAU-510 Sankeyaml dpendency check fix

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/LAU-489
This change is to upgrade gradle from 6.9.2 to 7.9.1
```
[ ] Yes
[x] No
```
> lau-489 Upgrade gradle to 7.5.1

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-512
This change is to remove suppression for log4j
```
[ ] Yes
[x] No
```
> LAU-512 remove suppression

- build.gradle
https://tools.hmcts.net/jira/browse/LAU-520
This change is to fix dependency check related to snakeyaml
```
[ ] Yes
[x] No
```
> LAU-520 dependency check fix

- audit.json
https://tools.hmcts.net/jira/browse/LAU-518
This change is to fix security scan .
```
[ ] Yes
[x] No
```
> LAU-518 security scan fix

- audit.json
- build.gradle
https://tools.hmcts.net/jira/browse/LAU-526
This change is to fix dependency check and security scan
```
[ ] Yes
[x] No
```
> LAU-526 dependency check fix

- audit.json
https://tools.hmcts.net/jira/browse/LAU-526
This Change is to fix dependency check.
```
[ ] Yes
[x] No
```
> LAU-526 Dependency Check failed

- src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/bdd/CaseSearchPostSteps.java
- src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/helper/CaseSearchPostHelper.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/utils/InputParamsVerifier.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/InputParamsVerifierPostExceptionTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/SearchInputParamsVerifierTest.java
https://tools.hmcts.net/jira/browse/LAU-496
Fix caseRefs validations
```
[ ] Yes
[ ] No
```
> LAU-496 Fix NPE and improve caseRef validations.

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/LAU-499
This change is about adding socketTimeout to JPA connection
```
[ ] Yes
[x] No
```
> LAU-499 Socket Timeout addition

- src/main/java/uk/gov/hmcts/reform/laubackend/cases/dto/ActionLog.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/dto/SearchLog.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/utils/CaseRefsUtils.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/utils/InputParamsVerifier.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseActionControllerTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseSearchControllerTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/dto/ActionLogTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/dto/SearchLogTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseActionServiceTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseSearchServiceTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/InputParamsVerifierPostExceptionTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/NotEmptyInputParamsVerifierTest.java
https://tools.hmcts.net/jira/browse/LAU-529
Tidy up all incoming caseRefs
```
[ ] Yes
[x] No
```
> LAU-529 Tidy up all incoming caseRefs.

- Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/LAU-524
This change is to disable nightly build during weekend
```
[ ] Yes
[x] No
```
> LAU-524 Disable nightly build during weekend

- build.gradle
https://tools.hmcts.net/jira/browse/LAU-553
This change is to fix dependency check related to spring-security and tomcat-embed
```
[ ] Yes
[x] No
```
> LAU-553 Dependency check fix

- README.md
https://tools.hmcts.net/jira/browse/LAU-546
Add SonarQube badges and Overview section
```
[ ] Yes
[x] No
```
> LAU-546 Add SonarQube badges and Overview section

- .github/PULL_REQUEST_TEMPLATE.md
- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/LAU-549
Cleanup helm release on success
```
[ ] Yes
[x] No
```
> LAU-549 Cleanup helm release on success

- .github/dependabot.yml
https://tools.hmcts.net/jira/browse/LAU-537
This change is to configure dependabot to lau-case-backend
```
[ ] Yes
[x] No
```
> Configuring Dependabot

- build.gradle
- charts/lau-case-backend/Chart.yaml
https://tools.hmcts.net/jira/browse/LAU-556
This change is for upgrading libraries
```
[ ] Yes
[x] No
```
> LAU-556 Upgrading libraries

- audit.json
- build.gradle
- charts/lau-case-backend/Chart.yaml
https://tools.hmcts.net/jira/browse/LAU-556
This change is to upgrade libraries related to io-rest-assured and java helm
```
[ ] Yes
[x] No
```
> LAU-556 upgrade more libraries

- build.gradle
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/LAU-569
Update postgresql lib.
```
[ ] Yes
[x] No
```
> LAU-569: Postgresql update

- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/LAU-563
Remove quotes from TF script.
```
[ ] Yes
[x] No
```
> LAU-563 remove quotes

- infrastructure/variables.tf
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/LAU-563
Fix to TF script.
```
[ ] Yes
[x] No
```
> LAU-563: Fix TF Script

- .dependabot/config.yml
- .github/dependabot.yml
https://tools.hmcts.net/jira/browse/LAU-572
This PR is to change dependabot configuration.
```
[ ] Yes
[x] No
```
> LAU-572 changing dependabot config

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-575
This change is to suppress CVE
```
[ ] Yes
[x] No
```
> LAU-575 suppressing CVE

- .github/workflows/ci.yml
- Jenkinsfile_CNP
- Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/LAU-555
Update github workflow action versions.
```
[ ] Yes
[x] No
```
> LAU-555: Update to resolve workflow deprecated versions.

- build.gradle
https://tools.hmcts.net/jira/browse/LAU-579
This change is to upgrade dependencies
```
[ ] Yes
[x] No
```
> LAU-579 dependency upgrade

- build.gradle
https://tools.hmcts.net/jira/browse/LAU-579
This change is to upgrade Junit
```
[ ] Yes
[x] No
```
> LAU-579 Junit upgrade

- Jenkinsfile_CNP
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-584
This change is to suppress CVE
```
[ ] Yes
[x] No
```
> LAU-548 Suppressing CVE

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-586
This change is to suppress CVE
```
[ ] Yes
[x] No
```
> LAU-586 Suppressing CVE

- build.gradle
https://tools.hmcts.net/jira/browse/LAU-571
This change includes libraries upgrade
```
[ ] Yes
[x] No
```
> LAU-571 Libraries upgrade

- .github/dependabot.yml
- build.gradle
https://tools.hmcts.net/jira/browse/LAU-611
This change is configure dependabot on Thursday at 6:00PM
```
[ ] Yes
[x] No
```
> LAU-611 dependabot configuration

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-618
This change is to fix suppress CVE-2022-1471
```
[ ] Yes
[x] No
```
> Lau-618 suppress CVE-2021-1471

- build.gradle
- config/owasp/suppressions.xml
Reverting suppression and fixing cve-2023-20861 
```
[ ] Yes
[x] No
```
> Spring-framework-CVE-2023-20861-fix

- src/main/resources/application.yaml
Remove unnecessary hikari configs
Remove unnecessary hikari configs
```
[ ] Yes
[x] No
```
> Remove unnecessary hikari configs

- audit.json
Update ignore cookies audit.json
```
[ ] Yes
[x] No
```
> Update ignore cookies audit.json

- src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditFindCaseRepository.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditRepository.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseSearchService.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditFindCaseRepositoryTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditRepositoryCaseRefTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditRepositoryTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseSearchServiceTest.java
https://tools.hmcts.net/jira/browse/LAU-614
Simplify case search query
```
[ ] Yes
[x] No
```
> Update case search query

- src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditFindCaseRepository.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseActionService.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseSearchService.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditRepositoryTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseActionServiceTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseSearchServiceTest.java
https://tools.hmcts.net/jira/browse/LAU-662
Return results sorted desc by timestamp (newest entries at the top)
```
[ ] Yes
[x] No
```
> LAU-662 return case action results in desc order

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-673
Suppress CVE-2023-20883
```
[ ] Yes
[x] No
```
> LAU-673 suppressing CVE-2023-20883

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-681
Suppress CVE-2023-35116
```
[ ] Yes
[x] No
```
> LAU-681 suppress CVE-2023-35116

- build.gradle
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/security/SecurityConfiguration.java
- src/main/resources/application.properties
https://tools.hmcts.net/jira/projects/LAU/issues/LAU-661
Bump Spring Boot from 3.0.8 to 3.1.1
```
[ ] Yes
[x] No
```
> LAU-661 bump Spring Boot from 3.0.8 to 3.1.1

- build.gradle
https://tools.hmcts.net/jira/browse/LAU-688
Bump tomcat to address CVE-2023-34981
```
[ ] Yes
[x] No
```
> LAU-688 bump tomcat to address CVE-2023-34981

- audit.json
https://tools.hmcts.net/jira/browse/LAU-719
This change is to fix security scan
```
[ ] Yes
[x] No
```
> LAU-719 Security scan fix

- audit.json
- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-722
Ignore CVE-2023-34040.
Ignore ZAProxy warnings
```
[ ] Yes
[x] No
```
> LAU-722 CVE-2023-34040

- audit.json
https://tools.hmcts.net/jira/browse/LAU-722
Ignore zaproxy warnings
```
[ ] Yes
[x] No
```
> Ignore zaproxy warnings

- build.gradle
https://tools.hmcts.net/jira/browse/LAU-730
Bump tomcat to address CVE-2023-41080
```
[ ] Yes
[x] No
```
> Lau 730 bump tomcat CVE 2023 41080

- build.gradle
https://tools.hmcts.net/jira/browse/LAU-763
Bump netty library
```
[ ] Yes
[x] No
```
> LAU-763 bump netty library

- charts/lau-case-backend/Chart.yaml
- infrastructure/main.tf
- infrastructure/variables.tf
LAU-733 Create lau-case flexible server
Create lau-case flexible server
```
[x] Yes
[] No
```
> Create lau-case flexible server

- infrastructure/main.tf
- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/serenityfunctionaltests/runner/CaseActionApiTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/serenityfunctionaltests/runner/CaseSearchApiTest.java
Add read user for postgres flexible
Add read user for postgres flexible
```
[ ] Yes
[x] No
```
> Add read user for postgres flexible [*** MERGE ONLY AFTER FLEXIBLE SERVER MIGRATION TONIGHT ***]

- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/serenityfunctionaltests/runner/CaseActionApiTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/serenityfunctionaltests/runner/CaseSearchApiTest.java
The functional tests were disabled to allow pipeline to pass for flexible server migration
```
[ ] Yes
[x] No
```
> Enable functional tests

- build.gradle
https://tools.hmcts.net/jira/browse/LAU-822
Bump spring boot to 3.1.6
```
[ ] Yes
[x] No
```
> LAU-822 bump spring to 3.1.6

- build.gradle
Bump junit plugin version for pitest.
```
[ ] Yes
[x] No
```
> Bump junit5Plugin version for pitest

- src/main/resources/application.yaml
Update application.yaml to use lauadmin to connect to db temporarily
```
[ ] Yes
[x] No
```
> LAU-783 use lauadmin temporarily

- charts/lau-case-backend/Chart.yaml
- charts/lau-case-backend/values.yaml
Update chart values to use flexible server. This should not make any difference while flux overwrites are in place.
```
[ ] Yes
[x] No
```
> LAU-783 update chart values to point to flexible server (also LAU-773)

- src/main/resources/db/migration/V012__Add_lauuser.sql
https://tools.hmcts.net/jira/browse/LAU-783
Create lauuser in flexible db
```
[ ] Yes
[x] No
```
> LAU-783 create lauuser via flyway in flexible server

- src/main/resources/application.yaml
Switch back to lauuser for db connection
```
[ ] Yes
[x] No
```
> LAU-783 switch back to lauuser for db connection

- infrastructure/main.tf
Remove single server db
```
[ ] Yes
[x] No
```
> LAU-783 remove single server db module

- infrastructure/main.tf
Remove flag, that disabled existing resource check under resource group presence
```
[ ] Yes
[x] No
```
> LAU-783 remove flag that disables resource check under resource group

- infrastructure/aat.tfvars
- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/LAU-829
Changing subnet expanded for aat 
```
[ ] Yes
[x] No
```
> LAU-829 adding subnet expended for aat

- build.gradle
Revert renovate update to fix the master build
Revert renovate update to fix the master build
```
[ ] Yes
[x] No
```
> Revert renovate update to fix the master build

- build.gradle
- charts/lau-case-backend/values.preview.template.yaml
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/config/FlywayCustomConfig.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/config/FlywayMigrationStrategyConfiguration.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/config/FlywayConfigurationTest.java
https://tools.hmcts.net/jira/browse/LAU-744
Bump flyway to v10.5.0
```
[ ] Yes
[x] No
```
> LAU-744 bump flyway to v10.5.0

- build.gradle
> Lau 744 bump flyway

- build.gradle
https://tools.hmcts.net/jira/browse/LAU-744
Bump flyway to version 10
> LAU-744 bump flyway

- build.gradle
Reverts hmcts/lau-case-backend#534
> Revert "LAU-744 bump flyway"

- charts/lau-case-backend/Chart.yaml
- charts/lau-case-backend/values.yaml
https://tools.hmcts.net/jira/browse/LAU-842
Enable spotInstances
> LAU-842 enable spot instances

- lib/applicationinsights.json
[LAU-847](https://tools.hmcts.net/jira/browse/LAU-847)
Disable dependency logs
> LAU-847 disable dependency tracking

- build.gradle
- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseActionController.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/security/SecurityConfiguration.java
- src/main/resources/application.yaml
Removed CVE suppressions. Adjusted security config.
> remove cve suppressions

- .github/workflows/swagger.yml
Add java distribution to swagger github workflow
> Add java distribution to swagger github workflow

- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/serenityfunctionaltests/runner/AccessRequestApiTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/serenityfunctionaltests/steps/AccessRequestGetApiSteps.java
- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/serenityfunctionaltests/steps/AccessRequestPostApiSteps.java
- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/serenityfunctionaltests/steps/BaseSteps.java
- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/serenityfunctionaltests/steps/CaseActionGetApiSteps.java
- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/serenityfunctionaltests/steps/CaseSearchGetApiSteps.java
- src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/bdd/AccessRequestGetSteps.java
- src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/bdd/AccessRequestPostSteps.java
- src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/helper/AccessRequestHelper.java
- src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/helper/RestHelper.java
- src/integrationTest/resources/features/get_access_request.feature
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/controllers/AccessRequestController.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/domain/AccessRequest.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/dto/AccessRequestLog.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/AccessRequestRepository.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/helpers/QueryBuilder.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/request/AccessRequestGetRequest.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/request/AccessRequestPostRequest.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/response/AccessRequestGetResponse.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/response/CaseActionGetResponse.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/service/AccessRequestService.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/utils/InputParamsVerifier.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/utils/NotEmptyInputParamsVerifier.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/controllers/AccessRequestControllerTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/helpers/QueryBuilderTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/service/AccessRequestServiceTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/InputParamsVerifierTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/NotEmptyInputParamsVerifierTest.java
LAU-933
Added GET access request endpoint
> Lau 933 access request get request

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/LAU-948
Creating the vault secret for encryption key
```
[ ] Yes
[x] No
```
> LAU-948 create new secret for encryption

- src/integrationTest/resources/application.yaml
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/LAU-946
Moving authorised services to Environment Variable
```
[ ] Yes
[x] No
```
> LAU-946 creating env-var for authorised services

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/LAU-948
Change in encryption key name
```
[ ] Yes
[x] No
```
> LAU-948 encryption key name change

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/LAU-948
Remove encryption key
```
[ ] Yes
[x] No
```
> LAU-948 remove unused encryption key

- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/serenityfunctionaltests/steps/AccessRequestGetApiSteps.java
- src/functionalTest/java/uk/gov/hmcts/reform/laubackend/cases/serenityfunctionaltests/steps/AccessRequestPostApiSteps.java
- src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/bdd/AccessRequestGetSteps.java
- src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/bdd/AccessRequestPostSteps.java
- src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/helper/AccessRequestHelper.java
- src/integrationTest/resources/features/post_access_request.feature
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/domain/AccessRequest.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/dto/AccessRequestLog.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/AccessRequestFindRepository.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/AccessRequestInsertRepository.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/helpers/QueryBuilder.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/request/AccessRequestGetRequest.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/service/AccessRequestService.java
- src/main/resources/db/migration/V017__Drop_request_start_timestamp_column.sql
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/dto/AccessRequestLogTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/AccessRequestRepositoryTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/helpers/QueryBuilderTest.java
- src/test/java/uk/gov/hmcts/reform/laubackend/cases/service/AccessRequestServiceTest.java
https://tools.hmcts.net/jira/browse/LAU-971
Remove startTimestamp and from GET/POST and update search to search by log_timestamp
```
[ ] Yes
[x] No
```
> Lau 971 remove start timestamp

- build.gradle
- src/integrationTest/resources/application.yaml
- src/main/resources/application.yaml
- src/test/resources/application.yaml
https://tools.hmcts.net/jira/browse/LAU-744
Update flyway to v11
```
[ ] Yes
[x] No
```
> LAU-744 Update flyway to v11

- infrastructure/main.tf
remove plpgsql azure extension
```
[ ] Yes
[x] No
```
> Update main.tf to remove plpgsql azure extension

- infrastructure/prod.tfvars
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/CME-130
Leave db monitoring only on prod env
```
[ ] Yes
[x] No
```
> CME-130 remove db monitoring from lower envs

- build.gradle
- infrastructure/import.tf
- infrastructure/main.tf
- infrastructure/prod.tfvars
- infrastructure/variables.tf
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/DTSPO-26425
Import block added for 'lau-case-backend-flexible-prod' DB server
```
[ ] Yes
[X] No
```
> Import block added for 'lau-case-backend-flexible-prod' DB server

- src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/bdd/AbstractSteps.java
- src/integrationTest/resources/features/post_case_search.feature
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/feign/FeignErrorDecoder.java
- src/main/java/uk/gov/hmcts/reform/laubackend/cases/feign/RetryableFeignConfig.java
Adding more logging
```
[ ] Yes
[x] No
```
> Integration test and logging

- src/main/java/uk/gov/hmcts/reform/laubackend/cases/feign/FeignErrorDecoder.java
https://tools.hmcts.net/jira/browse/LAU-905
Remove retry logging as it's working for all 5xx errors
```
[ ] Yes
[x] No
```
> LAU-905 remove retry logging as it's working
